Repository aws-samples/cql-replicator, pull requests merged in 2024-08, with the labels that each got.

#154 Better handling of original timestamp
  glue/README.MD
  glue/sbin/keyspaces/CQLReplicator.scala
Labels: enhancement

#159 Fix typo in README.MD
  glue/README.MD
Labels: documentation

#161 Fix the issue with the glueStreaming parameter. GLUE_TYPE is gluestre…
  glue/bin/cqlreplicator
  glue/resources/CQLReplicator-calculator.xlsx
Labels: bug
